apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # In local, we want APP_ENV=local
  - target:
      kind: ConfigMap
      name: kairos-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: local
