import logging
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.models.alert_rule import AlertRule
from app.db.models.rule_definition import RuleDefinition
from app.db.models.alert_condition import AlertCondition
from app.db.models.enums import AlertSeverity, SignalType, AlertOperator

logger = logging.getLogger(__name__)

async def seed_alerts(db: AsyncSession, service_id: UUID) -> None:
    """
    Seeds initial alert rules and policies, but explicitly DOES NOT seed Signals or Alerts.
    Those should only be generated by live ingestion or automated test suites.
    """
    logger.info(f"Seeding Alert Rules for Service {service_id}")
    
    # 1. High CPU Rule
    rule = AlertRule(
        service_id=service_id,
        name="High CPU Usage",
        slug="high-cpu-usage",
        description="Fires when CPU exceeds 90% for 5 minutes",
        severity=AlertSeverity.CRITICAL,
        evaluation_window="5m",
        cooldown="15m"
    )
    db.add(rule)
    await db.flush()
    
    definition = RuleDefinition(
        rule_id=rule.id,
        version=1,
        conditions_payload=[{"type": "cpu", "threshold": 90}]
    )
    db.add(definition)
    await db.flush()
    
    condition = AlertCondition(
        definition_id=definition.id,
        signal_type=SignalType.METRIC,
        metric_name="system.cpu.usage",
        operator=AlertOperator.GREATER_THAN,
        threshold=90.0,
        duration_seconds=300
    )
    db.add(condition)
    
    await db.commit()
    logger.info(f"Alert Rules seeded for Service {service_id}")
