from enum import Enum


class ResourceType(str, Enum):
    USER = "USER"
    ORGANIZATION = "ORGANIZATION"
    PROJECT = "PROJECT"
    SERVICE = "SERVICE"
    ENVIRONMENT = "ENVIRONMENT"
    INCIDENT = "INCIDENT"
    ALERT = "ALERT"
    BACKGROUND_TASK = "BACKGROUND_TASK"
    NOTIFICATION = "NOTIFICATION"
    AI_ANALYSIS = "AI_ANALYSIS"
    ROLE = "ROLE"
    PERMISSION = "PERMISSION"
