"""add username and base model

Revision ID: 1d5ed61f4119
Revises: cb122f8a34f5
Create Date: 2026-07-26 09:16:13.319610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d5ed61f4119"
down_revision: str | Sequence[str] | None = "cb122f8a34f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=100), nullable=False))
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###
